### ISSUE TITLE
Don't mention Lenna.png in docs

### ISSUE THREAD

**Issue by RollingStar** [0x09/resdet#9]
https://en.wikipedia.org/wiki/Lenna#Criticism

Lenna comes from a Playboy centerfold. It doesn't seem appropriate to use as a general-purpose example.

**Comment by 0x09** [comment]
@RollingStar the example now uses a reduced size version of the public domain [Blue Marble 2012](https://www.nasa.gov/multimedia/imagegallery/image_feature_2159.html) which is also actually better for demonstrating resdet as it turns out.
 https://github.com/0x09/resdet/commit/7dfef1059ee2e456a23fc5d79262ca75371aef4c

[dspfun](https://github.com/0x09/dspfun) has been updated as well as the newer subprojects there had already adopted a different, CC0 example image, so this is now used more consistently:
https://github.com/0x09/dspfun/commit/e34b65c2015d38a613837928bd7cbd9b4c61a87c
https://github.com/0x09/dspfun/commit/d77fb9e480ad811610837f71741da5a36b3a98b7

**Comment by RollingStar** [comment]
Thank you!
